### ISSUE TITLE
design wishlist implementation

### ISSUE THREAD

**Issue by billythakidd04** [rbaia28/mew.co#4]
what attributes need to be tracked per wishlist request?

so far we know we have:
- id
- userid
- pokemonid - is this the pokedex number or something else?
- attributes: here we need to decide on the proper implementation

shiny
shadow
level minimum
region

We might need to tie this to an attribute table... Not sure yet.

**Comment by rbaia28** [comment]
- level min for the pokemon will be changed when traded depending on the trainer level so I don't know if that's the best option for the trading thing. We should set a min cp though so that way people arent trading a 14 cp something for a 2100 cp. 
- we should probably include gender as well in the gen layout because M vs. F forms for the newer ones are optically different but the number remains the same. its more for those looking for the fully completed dex than anything. i know which ones change though so were gucci there
- I found this, its missing gen 8 but I can toss this in if we like this layout https://docs.google.com/spreadsheets/d/1MGcNBb8irm98M9_q2Jxg_NG9nY7rB0FG4CXeTK8g2H0/edit#gid=2 
- This has a ton of great info
https://pokemondb.net/about


All of this has been included in the google drive

**Comment by billythakidd04** [comment]
hmmmm this should move to a trello discussion... I think we need to better lay out the requirements and then redo this ticket

**Comment by billythakidd04** [comment]
closing this until we have a useful understanding of the problem

**Comment by billythakidd04** [comment]
moved to https://docs.google.com/document/d/12fI5p0jWgCIZpUTbSVd-pC1hjBoUHe03wkv4yYlvVpw/edit?usp=sharing for cleanup and reconciliation.
